### ISSUE TITLE
 'SplatfactoModel' has no attribute 'strategy' when training DiG

### ISSUE THREAD

**Issue by perrydoremi** [kerrj/rsrd#4]
Hi, thanks for this interesting work, 
Recently I was tring to reimplement the project. Following the instructions, I have finish training the GARField and was about training the DiG, however I'm encountered this issue:

![Screenshot from 2024-11-25 15-21-57](https://github.com/user-attachments/assets/0801aa37-a6b9-4a6d-b0bc-98067ccf2740)

I checked the nerfstudio installation (1.1.4):
`Python 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from nerfstudio.models.splatfacto import SplatfactoModelConfig, SplatfactoModel
>>> dir(SplatfactoModel)
['T_destination', '__annotations__', '__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_apply', '_apply_bilateral_grid', '_call_impl', '_compiled_call_impl', '_downscale_if_required', '_get_background_color', '_get_backward_hooks', '_get_backward_pre_hooks', '_get_downscale_factor', '_get_name', '_load_from_state_dict', '_maybe_warn_non_full_backward_hook', '_named_members', '_register_load_state_dict_pre_hook', '_register_state_dict_hook', '_replicate_for_data_parallel', '_save_to_state_dict', '_slow_forward', '_version', '_wrapped_call_impl', 'add_module', 'after_train', 'apply', 'bfloat16', 'buffers', 'call_super_init', 'children', 'colors', 'compile', 'composite_with_background', 'cpu', 'cuda', 'cull_gaussians', 'device', 'double', 'dump_patches', 'dup_gaussians', 'dup_in_all_optim', 'dup_in_optim', 'eval', 'extra_repr', 'features_dc', 'features_rest', 'float', 'forward', 'get_buffer', 'get_empty_outputs', 'get_extra_state', 'get_gaussian_param_groups', 'get_gt_img', 'get_image_metrics_and_images', 'get_loss_dict', 'get_metrics_dict', 'get_outputs', 'get_outputs_for_camera', 'get_outputs_for_camera_ray_bundle', 'get_param_groups', 'get_parameter', 'get_rgba_image', 'get_submodule', 'get_training_callbacks', 'half', 'ipu', 'k_nearest_sklearn', 'load_model', 'load_state_dict', 'means', 'modules', 'mtia', 'named_buffers', 'named_children', 'named_modules', 'named_parameters', 'num_points', 'opacities', 'parameters', 'populate_modules', 'quats', 'refinement_after', 'register_backward_hook', 'register_buffer', 'register_forward_hook', 'register_forward_pre_hook', 'register_full_backward_hook', 'register_full_backward_pre_hook', 'register_load_state_dict_post_hook', 'register_load_state_dict_pre_hook', 'register_module', 'register_parameter', 'register_state_dict_post_hook', 'register_state_dict_pre_hook', 'remove_from_all_optim', 'remove_from_optim', 'requires_grad_', 'scales', 'set_background', 'set_crop', 'set_extra_state', 'set_submodule', 'share_memory', 'shs_0', 'shs_rest', 'split_gaussians', 'state_dict', 'step_cb', 'to', 'to_empty', 'train', 'type', 'update_to_step', 'xpu', 'zero_grad']

>>> dir(SplatfactoModelConfig)
['__annotations__', '__class__', '__dataclass_fields__', '__dataclass_params__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'background_color', 'color_corrected_metrics', 'continue_cull_post_densification', 'cull_alpha_thresh', 'cull_scale_thresh', 'cull_screen_size', 'densify_grad_thresh', 'densify_size_thresh', 'enable_collider', 'eval_num_rays_per_chunk', 'grid_shape', 'max_gauss_ratio', 'n_split_samples', 'num_downscales', 'num_random', 'output_depth_during_training', 'prompt', 'random_init', 'random_scale', 'rasterize_mode', 'refine_every', 'reset_alpha_every', 'resolution_schedule', 'setup', 'sh_degree', 'sh_degree_interval', 'split_screen_size', 'ssim_lambda', 'stop_screen_size_at', 'stop_split_at', 'use_bilateral_grid', 'use_scale_regularization', 'warmup_length']
>>> 
`
As you see, I can't find 'strategy' attributes from nerfstudio.models.splatfacto import SplatfactoModelConfig, SplatfactoModel. 

Again, thanks for this interesting work!!!

**Comment by kerrj** [comment]
Hm can you try installing nerfstudio from source? We might have listed the wrong nerfstudio version in the readme

**Comment by perrydoremi** [comment]
Thanks!
I've already installed the nerfstudio and gsaplt from source, however it turns out that:

![Screenshot from 2024-11-27 16-46-58](https://github.com/user-attachments/assets/feee4bdb-a559-4b91-94d0-31143e9f6858)

After revised `dig/dig.py` line234 'SplatfactoModel.strategy.step_pre_backward' into 'self.strategy.step_pre_backward', the Dig training worked.

**Comment by kerrj** [comment]
Ok! that's odd the current dig.py version linked in the submodule already has self.strategy instead of SplatfactoModel.strategy, but maybe that was updated after you pulled to install.
